"""health_snapshot — auto-generate the Aegis program health page.

Writes brain/projects/aegis-health/aegis-health-latest.md: one page holding
current git state of both repos, the STATUS.md headline, pending attended
decisions, and the session-memory current-state block. refresh_aegis.py calls
this FIRST, then ingests the page like any other notes channel — so
brain_query and the MCP session_briefing tool both serve it.

Deterministic and idempotent: same inputs -> same page (timestamp aside).
Secrets policy: this generator reads only tracked repo files and git
metadata — never .env, never key material.

Usage:  python tools/health_snapshot.py
"""

from __future__ import annotations

import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

HOME = Path.home()
ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "brain" / "projects" / "aegis-health"
OUT = OUT_DIR / "aegis-health-latest.md"

REPOS = {
    "aegis-finance": HOME / "aegis-finance",
    "Aegis module": HOME / "Aegis module",
}
STATUS_MD = HOME / "Aegis module" / "STATUS.md"
MEMORY_MD = (HOME / ".claude/projects/C--Users-mrthn-aegis-finance"
             / "memory" / "MEMORY.md")


def _git(repo: Path, *args: str) -> str:
    try:
        r = subprocess.run(["git", "-C", str(repo), *args],
                           capture_output=True, text=True, timeout=20)
        return r.stdout.strip()
    except Exception as e:  # noqa: BLE001 — health page reports, never raises
        return f"(git unavailable: {type(e).__name__})"


def _head(path: Path, n: int) -> str:
    if not path.exists():
        return f"(missing: {path})"
    return "\n".join(path.read_text(encoding="utf-8",
                                    errors="replace").splitlines()[:n])


def _memory_current_state() -> str:
    text = _head(MEMORY_MD, 200)
    m = re.search(r"## Current state.*?(?=\n## )", text, re.S)
    return m.group(0).strip() if m else "(no Current state block found)"


def _pending(status_text: str) -> str:
    hits = re.findall(r"[^.\n]*(?:PENDING|ATTENDED DECISION[^:]*)\s*:?[^.]*\.",
                      status_text)
    return "\n".join(f"- {h.strip()}" for h in hits[:8]) or "- (none parsed)"


def main() -> int:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    status_head = _head(STATUS_MD, 45)

    lines = [
        "---",
        "name: aegis-health-latest",
        "description: Auto-generated Aegis program health snapshot — git state "
        "of both repos, STATUS headline, pending attended decisions, session-"
        "memory current state. Regenerated by tools/refresh_aegis.py.",
        "---",
        "",
        f"# Aegis program health — generated {stamp}",
        "",
        "AUTO-GENERATED by optimus/tools/health_snapshot.py — do not edit; "
        "run tools/refresh_aegis.py to regenerate.",
        "",
        "## Repos",
        "",
    ]
    for name, repo in REPOS.items():
        dirty = _git(repo, "status", "--porcelain")
        lines += [
            f"### {name}",
            f"- HEAD: `{_git(repo, 'log', '-1', '--format=%h %ad %s',
                             '--date=short')}`",
            f"- branch: `{_git(repo, 'rev-parse', '--abbrev-ref', 'HEAD')}`",
            f"- working tree: {'CLEAN' if not dirty else f'DIRTY ({len(dirty.splitlines())} paths)'}",
            "",
        ]
    lines += [
        "## Pending attended decisions (parsed from STATUS.md)",
        "",
        _pending(status_head),
        "",
        "## STATUS.md headline (Aegis module)",
        "",
        "```",
        status_head,
        "```",
        "",
        "## Session-memory current state",
        "",
        _memory_current_state(),
        "",
    ]
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"[ok] wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
